---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
        - 1.9.3
        - 2.1.0
script: bundle exec rake test
env:
        - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
        - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
        - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
        - PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes DEPLOY_TO_FORGE=yes
      
matrix:
        exclude:
                - rvm: 1.9.3
                  env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
                - rvm: 1.9.3
                  env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes DEPLOY_TO_FORGE=yes

deploy:
        provider: puppetforge
        user: cirrax
        password:
                secure: z2DJM4VOFbCUWO5+1qFFqiUuj/87Qwa+uZJLNLr8n9zxbnWCa1VZSPquHgb8KUHjcnlqveCMHIWefEcBSUTVNaeQchJhi+dMFilYtAqUp7tdwXD9bvBjtX/cAI/jxFNA0O8w91ZymgdxK0NE+6nlRbitJ79h5GqMaHYdRUvbEOySuuuQx4A65YL4j8zEjpwz1Cl8sR4G4QL7596p0KOzgp5QtS4y0dIJzBHa40jBl59edZyESWY+lNKH9hBcYjhreLqjvLLOA5cMyUhmO3zimcVnEvMhnU9i9b7+uUJMBwXisQ0N/1uATnE8vvhJEUfSN99WmkGEkzXb2KoIDyw+ENcz0LB0akHVAI7v30+OsISDLeDjJSBO0JY7oQLyWuAlFSuAa5NFIXFTLJ5QWVSR0gCMr0J6bXvEivIiTAtl79Bi8PiT402YhXgSvEkZUwPFFJkoq6Pw4maJYwBKlqGHRIeLv1ZxW1ZmxOyjzRZxPIo+f4NSLPfKo/a/Z7nmixRxnubaJgow6+0gQfZn8zmE3m/j+swzGVKzfcCNXGPtaAFC5s0SPgwSzrhSurfxu52mfS4jBiSEk3gZXIE/eygFMmhu9EFAcFBRl4P0rR1lEbVNV9tKQ1srppXmJMFansDS95n6vQkR4vVCpuRMIJ4rskkMvkIM5W90sQFgJsNruGM=
        on:
            tags: true
            # all_branches is required to use tags
            all_branches: true
            # Only publish the build marked with "DEPLOY_TO_FORGE"
            condition: "$DEPLOY_TO_FORGE = yes"
